from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


DEFAULT_CONFIG_PATH = ".ai-issue-worker.yaml"
REASONING_EFFORTS = ("low", "medium", "high", "xhigh")


class ConfigError(ValueError):
    pass


@dataclass
class PathsConfig:
    worktree_root: str = ".ai-worktrees"
    run_root: str = ".ai-runs"
    log_root: str = ".ai-logs"
    runtime_root: str = ".ai-runtime"


@dataclass
class SchedulerConfig:
    interval_minutes: int = 30


@dataclass
class IssueSelectionConfig:
    ready_label: str = "ai-ready"
    working_label: str = "ai-working"
    failed_label: str = "ai-failed"
    pr_opened_label: str = "ai-pr-opened"
    blocked_labels: list[str] = field(default_factory=lambda: ["blocked", "needs-human"])
    respect_issue_dependencies: bool = True
    max_issues_per_run: int = 1
    selection_order: str = "oldest_updated"


@dataclass
class GitConfig:
    branch_prefix: str = "ai/issue-"
    keep_worktree_on_success: bool = False
    keep_worktree_on_failure: bool = True
    commit_message_template: str = "Fix issue #{number}: {title}"
    allow_dirty_base: bool = False
    remove_ready_on_pr: bool = False


@dataclass
class AgentConfig:
    backend: str = "codex"
    command: str = "codex exec --full-auto"
    model: str | None = "gpt-5.4"
    reasoning: str | None = "high"
    timeout_minutes: int = 30
    max_repair_attempts: int = 1


@dataclass
class ReviewConfig:
    enabled: bool = True
    command: str = "codex exec --sandbox read-only"
    max_iterations: int = 3
    fix_priorities: list[str] = field(default_factory=lambda: ["P0", "P1"])


@dataclass
class VerifyConfig:
    commands: list[str] = field(
        default_factory=lambda: ["ruff check .", "ruff format --check .", "pyright", "pytest"]
    )
    run_all_commands: bool = True


@dataclass
class DiffPolicyConfig:
    max_changed_files: int = 30
    max_diff_lines: int = 2000
    reject_paths: list[str] = field(default_factory=lambda: [".env", ".secrets", "**/*.pem", "**/*.key"])
    allow_lockfile_changes: bool = False


@dataclass
class PRConfig:
    draft: bool = True
    title_template: str = "Fix #{number}: {title}"
    body_template: str = (
        "Closes #{number}\n\n"
        "## Summary\n"
        "This PR was generated by the local AI issue worker.\n\n"
        "## Verification\n"
        "{verification_summary}\n\n"
        "## Changed files\n"
        "{changed_files}\n\n"
        "## Agent notes\n"
        "{agent_notes}\n"
    )


@dataclass
class WorkerConfig:
    repo: str
    base_branch: str = "main"
    paths: PathsConfig = field(default_factory=PathsConfig)
    scheduler: SchedulerConfig = field(default_factory=SchedulerConfig)
    issue_selection: IssueSelectionConfig = field(default_factory=IssueSelectionConfig)
    git: GitConfig = field(default_factory=GitConfig)
    agent: AgentConfig = field(default_factory=AgentConfig)
    review: ReviewConfig = field(default_factory=ReviewConfig)
    verify: VerifyConfig = field(default_factory=VerifyConfig)
    diff_policy: DiffPolicyConfig = field(default_factory=DiffPolicyConfig)
    pr: PRConfig = field(default_factory=PRConfig)


def _merge(default: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(default)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def default_config_dict(repo: str = "owner/repo") -> dict[str, Any]:
    return {
        "repo": repo,
        "base_branch": "main",
        "paths": PathsConfig().__dict__,
        "scheduler": SchedulerConfig().__dict__,
        "issue_selection": IssueSelectionConfig().__dict__,
        "git": GitConfig().__dict__,
        "agent": AgentConfig().__dict__,
        "review": ReviewConfig().__dict__,
        "verify": VerifyConfig().__dict__,
        "diff_policy": DiffPolicyConfig().__dict__,
        "pr": PRConfig().__dict__,
    }


def config_from_dict(data: dict[str, Any]) -> WorkerConfig:
    if not data.get("repo"):
        raise ConfigError("config field 'repo' is required")
    data = dict(data)
    if isinstance(data.get("agent"), dict):
        agent = dict(data["agent"])
        if "reasoning_effort" in agent:
            agent.setdefault("reasoning", agent.pop("reasoning_effort"))
        data["agent"] = agent
    raw = _merge(default_config_dict(repo=data["repo"]), data)
    config = WorkerConfig(
        repo=raw["repo"],
        base_branch=raw.get("base_branch", "main"),
        paths=PathsConfig(**raw["paths"]),
        scheduler=SchedulerConfig(**raw["scheduler"]),
        issue_selection=IssueSelectionConfig(**raw["issue_selection"]),
        git=GitConfig(**raw["git"]),
        agent=AgentConfig(**raw["agent"]),
        review=ReviewConfig(**raw["review"]),
        verify=VerifyConfig(**raw["verify"]),
        diff_policy=DiffPolicyConfig(**raw["diff_policy"]),
        pr=PRConfig(**raw["pr"]),
    )
    if config.agent.reasoning and config.agent.reasoning not in REASONING_EFFORTS:
        allowed = ", ".join(REASONING_EFFORTS)
        raise ConfigError(f"agent.reasoning must be one of: {allowed}")
    if config.review.max_iterations < 1:
        raise ConfigError("review.max_iterations must be at least 1")
    invalid_priorities = [priority for priority in config.review.fix_priorities if priority not in {"P0", "P1"}]
    if invalid_priorities:
        raise ConfigError("review.fix_priorities must contain only P0 or P1")
    return config


def load_config(path: Path) -> WorkerConfig:
    if not path.exists():
        raise ConfigError(f"config file not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ConfigError("config file must contain a YAML mapping")
    return config_from_dict(data)


def default_config_text() -> str:
    data = default_config_dict()
    body = yaml.safe_dump(data, sort_keys=False)
    return (
        "# Local AI Issue Worker configuration\n"
        "# Replace repo with the target GitHub repository in owner/repo form.\n"
        "# Verifier commands run inside the issue worktree and are trusted local config.\n"
        f"{body}"
    )


def write_default_config(path: Path, force: bool = False) -> None:
    if path.exists() and not force:
        raise ConfigError(f"config already exists: {path}; use --force to overwrite")
    path.write_text(default_config_text(), encoding="utf-8")
